server:
  port: 8080
debug:
  false
person:
  last-name: lucy
  age: 18
  boss: false
  birth: 2017/09/07
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: dog1
    age: 2
